# Generated by Django 5.0.6 on 2024-07-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('item_price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
